### ISSUE TITLE
create DB file failed

### ISSUE THREAD

**Issue by GTrunSec** [dsnezhkov/deepsea#1]
test command and output info:

```
../../deepsea --config ./campaign.yaml  storage query -d ./campaign.db -t createtable
INFO 2019/12/14 19:32:48 viper.go:1243: Attempting to read in config file
DEBUG 2019/12/14 19:32:48 viper.go:1253: Reading file:  ./campaign.yaml
DEBUG 2019/12/14 19:32:48 root.go:89: Using config file:  ./campaign.yaml
DEBUG 2019/12/14 19:32:48 storage.go:32: storageDriver()
INFO 2019/12/14 19:32:48 storage.go:57: `storage` is a meta command. Please use subcommands. `-h` is for help 
STORAGE: Manage data in persistent record storage
```
platform: NIXOS and Debian(same error's output info):
But in this case,  I link my test files and deepsea-evn-info. 
https://github.com/hardenedlinux/NSM-data-analysis/tree/master/test/deepsea

**Comment by dsnezhkov** [comment]
Hi, 

Thanks for reporting. 
a. The command line options overriding the configuration file directives in `storage` module were not honored. 
b. Plus, there was an incorrect assumption on empty DB file existence (see #2 ).

If you pull the master it has a temporary change before #2 is addressed (I will drop the binary later). 

Temp fix: 
1. `touch /path/to/campaign.db` 
2. Load marks
```
../../deepsea  --config campaign1.yaml  storage -d ./campaign.db  load -s ./marks.csv
```
2(b) Optional if need to just create a table:
 ```
../../deepsea  --config campaign1.yaml  storage  -d ./campaign.db manager  -T createtable
```

**Comment by dsnezhkov** [comment]
Also, one more thing:

The latest code base gains TRACE/DEBUG levels useful for introspecting the steps.

```
../../deepsea  -t  --config campaign1.yaml  storage  -d campaign.db manager  -T createtable
INFO 2019/12/14 20:07:52 viper.go:1243: Attempting to read in config file
DEBUG 2019/12/14 20:07:52 viper.go:1253: Reading file:  campaign1.yaml
DEBUG 2019/12/14 20:07:52 root.go:90: Using config file:  campaign1.yaml
DEBUG 2019/12/14 20:07:52 manager.go:38: managerDriver()
DEBUG 2019/12/14 20:07:52 manager.go:83: Setting DBFile link
ERROR 2019/12/14 20:07:52 manager.go:86: Database file does not exist: campaign.db
```

`touch campaign.db`

```
../../deepsea  -t  --config campaign1.yaml  storage  -d campaign.db manager  -T createtable
INFO 2019/12/14 20:08:26 viper.go:1243: Attempting to read in config file
DEBUG 2019/12/14 20:08:26 viper.go:1253: Reading file:  campaign1.yaml
DEBUG 2019/12/14 20:08:26 root.go:90: Using config file:  campaign1.yaml
DEBUG 2019/12/14 20:08:26 manager.go:38: managerDriver()
DEBUG 2019/12/14 20:08:26 manager.go:83: Setting DBFile link
TRACE 2019/12/14 20:08:26 manager.go:98: Making a Collection
TRACE 2019/12/14 20:08:26 manager.go:101: Getting a DBTask
DEBUG 2019/12/14 20:08:26 manager.go:104: Found Valid Task: createtable
TRACE 2019/12/14 20:08:26 manager.go:107: Converting Task to a function call
INFO 2019/12/14 20:08:26 manager.go:158: Creating Marks table
```

```
../../deepsea  -t  --config campaign1.yaml  storage  -d campaign.db load -s  marks.csv
INFO 2019/12/14 20:09:02 viper.go:1243: Attempting to read in config file
DEBUG 2019/12/14 20:09:02 viper.go:1253: Reading file:  campaign1.yaml
DEBUG 2019/12/14 20:09:02 root.go:90: Using config file:  campaign1.yaml
DEBUG 2019/12/14 20:09:02 load.go:40: loadDriver()
DEBUG 2019/12/14 20:09:02 load.go:119: Selecting the mark table
INFO 2019/12/14 20:09:02 manager.go:142: Removing existing rows (if any)
DEBUG 2019/12/14 20:09:02 load.go:128: Matched Source File as a CSV file
DEBUG 2019/12/14 20:09:02 load.go:131: Converting CSV2JSON for DB Load
TRACE 2019/12/14 20:09:02 load.go:137: [{"ident":"\u003cdynamic\u003e","email":"user@gmail.com","firstname":"","lastname":""}]
DEBUG 2019/12/14 20:09:02 load.go:139: Unmarshal JSON into Marks
DEBUG 2019/12/14 20:09:02 load.go:145: Loading Marks into DB
DEBUG 2019/12/14 20:09:02 load.go:149: [1] Loading Mark
TRACE 2019/12/14 20:09:02 load.go:161: Mark has dynamic ID
DEBUG 2019/12/14 20:09:02 load.go:174: Checks Passed. Inserting record.
TRACE 2019/12/14 20:09:02 load.go:185: Finding all marks
TRACE 2019/12/14 20:09:02 load.go:191: Getting all marks from collection
INFO 2019/12/14 20:09:02 load.go:198: -= = = =  Marks = = = =-
DEBUG 2019/12/14 20:09:02 manager.go:120: Querying for result : find()
lsxbtvwd, user@gmail.com, , .
```

**Comment by GTrunSec** [comment]
thank you for explaining that. currently, I'm on deepsea master rev. I tried using your solution 
```
../../result/bin/deepsea --config campaign1.yaml storage  -d campaign.db manager  -T createtable                                       
Error: unknown shorthand flag: 'd' in -d                                                                                                 
Usage:                                                                                                                                   
  DeepSea storage manager [flags]                                                                                                        
                                                                                                                                         
Flags:                                                                                                                                   
  -D, --DBFile string   Path to QL DB file                                                                                               
  -T, --DBTask string   Tasks to run:                                                                                                    
                        showmarks                                                                                                        
                        truncate
                        droptable
                        createtable
                        recycletable
  -h, --help            help for manager

Global Flags:
      --config string   config file (required)
  -v, --debug           DEBUG output
  -i, --info            INFO output
  -t, --trace           TRACE output

FATAL 2019/12/14 18:28:31 Execute(): Cobra.Command: unknown shorthand flag: 'd' in -d
```
So，I changed arg of -d  to -D. everything is good.
I have seen your newer commites. you have been fixed this problem. just Ignore this reply.
```
: NSM-data-analysis/test/deepsea ‹master*›                                                                                        
» ../../result/bin/deepsea -t --config campaign1.yaml storage  -D campaign.db manager  -T createtable                                    
INFO 2019/12/14 18:29:04 viper.go:1243: Attempting to read in config file                                                                
DEBUG 2019/12/14 18:29:04 viper.go:1253: Reading file:  campaign1.yaml                                                                   
DEBUG 2019/12/14 18:29:04 root.go:89: Using config file:  campaign1.yaml                                                                 
DEBUG 2019/12/14 18:29:04 manager.go:38: managerDriver()                                                                                 
DEBUG 2019/12/14 18:29:04 manager.go:98: Setting DBFile link                                                                             
TRACE 2019/12/14 18:29:04 manager.go:113: Making a Collection                                                                            
TRACE 2019/12/14 18:29:04 manager.go:116: Getting a DBTask                                                                               
DEBUG 2019/12/14 18:29:04 manager.go:119: Found Valid Task: createtable                                                                  
TRACE 2019/12/14 18:29:04 manager.go:122: Converting Task to a function call                                                             
INFO 2019/12/14 18:29:04 manager.go:173: Creating Marks table       
```

**Comment by GTrunSec** [comment]
one more question. did you test the argument of mailclient?
```
 NSM-data-analysis/test/deepsea ‹master*›                                                                                [10/682]
» ../../result/bin/deepsea -t mailclient --config campaign1.yaml                                                                         
panic: unable to redefine 't' shorthand in "mailclient" flagset: it's already used for "TLS" flag                                        
                                                                                                                                         
goroutine 1 [running]:                                                                                                                   
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0000e3100, 0xc000298820)                                                                    
        /build/go/src/github.com/spf13/pflag/flag.go:862 +0x6d7                                                                          
github.com/spf13/pflag.(*FlagSet).AddFlagSet.func1(0xc000298820)                                                                         
        /build/go/src/github.com/spf13/pflag/flag.go:875 +0xa8                                                                           
github.com/spf13/pflag.(*FlagSet).VisitAll(0xc0000e3800, 0xc00014fbd0)                                                                   
        /build/go/src/github.com/spf13/pflag/flag.go:278 +0x94                                                                           
github.com/spf13/pflag.(*FlagSet).AddFlagSet(0xc0000e3100, 0xc0000e3800)
        /build/go/src/github.com/spf13/pflag/flag.go:873 +0x58
github.com/spf13/cobra.(*Command).mergePersistentFlags(0x11b70c0)
        /build/go/src/github.com/spf13/cobra/command.go:1572 +0x90
github.com/spf13/cobra.stripFlags(0xc000284f30, 0x3, 0x3, 0x11b70c0, 0x2, 0x1, 0x3)
        /build/go/src/github.com/spf13/cobra/command.go:538 +0x51
github.com/spf13/cobra.(*Command).Find.func1(0x11b70c0, 0xc000284f30, 0x3, 0x3, 0xa, 0xc000284f30, 0x3, 0x3)
        /build/go/src/github.com/spf13/cobra/command.go:597 +0x5c
github.com/spf13/cobra.(*Command).Find.func1(0x11b7ac0, 0xc0000d6010, 0x4, 0x4, 0x1, 0x1, 0x7, 0xc40ad2)
        /build/go/src/github.com/spf13/cobra/command.go:605 +0x119
github.com/spf13/cobra.(*Command).Find(0x11b7ac0, 0xc0000d6010, 0x4, 0x4, 0x6, 0x6, 0xd2fe60, 0x6, 0xd2fe60, 0xd2fe60)
        /build/go/src/github.com/spf13/cobra/command.go:610 +0x8c
github.com/spf13/cobra.(*Command).ExecuteC(0x11b7ac0, 0xc0000e2118, 0xc0000e2120, 0xc0000e2128)
        /build/go/src/github.com/spf13/cobra/command.go:895 +0x60c
```

**Comment by dsnezhkov** [comment]
Yeah, so I have been mostly driving from the config file for my use case, and I need to get the option names in order for the command line.  This is most likely a regression, much like `-d` and `-D` you have noticed.  Thanks, I will look into it soon.

**Comment by dsnezhkov** [comment]
@GTrunSec  as I suspected - a regression on TLS. I changed in to `-l` to get you going but will be addressing in  #3 . 


```
./deepsea  mailclient  -h
MAILCLIENT: Connect and Email a phish with features

Usage:
  DeepSea mailclient [flags]

Flags:
  -F, --From string           Message From: header
  -H, --HTMLTemplate string   HTML Template file (.htpl)
  -p, --SMTPPort int          SMTP server port (default 25)
  -s, --SMTPServer string     SMTP server (default "127.0.0.1")
  -U, --SMTPUser string       SMTP user (default "testuser")
  -S, --Subject string        Message Subject: header
  -l, --TLS string            Use TLS handshake (STARTTLS) (default "yes")
  -P, --TextTemplate string   Text Template file (.ttpl)
  -T, --To string             Message To: header
  -h, --help                  help for mailclient

Global Flags:
      --config string   config file (required)
  -v, --debug           DEBUG output
  -i, --info            INFO output
  -t, --trace           TRACE output
```

Thanks!

**Comment by GTrunSec** [comment]
🎉 Thank you for helping. Done for all test commands.  I think this project really helpful do a phishing test on an internal network of the SMTP protocol.  I'm going to using Zeek script which has recorded all email info on an internal network. then I write a script for the Zeek SMTP log that can be parsed CSV Date add to deepsea phishing.

**Comment by dsnezhkov** [comment]
Thanks for the feedback. Let me know if any issues.
